### PR TITLE
Add WattAdvisor repo

### PR DESCRIPTION
**Pull request by jonas912**

### CODE REVIEW

**Comment by netomi** [comment]
LGTM, if you add a project lead as reviewer and get approval you can merge yourself using `/otterdog merge` later on.

**Comment by jonas912** [comment]
@netomi Who is a project lead? The belonging group in this project is empty: https://github.com/orgs/eclipse-wattadvisor/teams/technology-wattadvisor-project-leads

**Comment by netomi** [comment]
hmm it looks like the project has no leads yet: https://projects.eclipse.org/projects/technology.wattadvisor/who

I will merge that PR for now and I will raise that with our EMO team.

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
ok so the repo has been created, it might take up to 3h for the permissions to be set accordingly. You can already create a fork and prepare a PR though.

**Pull request merged**
